---
- name: Homebrew Packages
  hosts: localhost
  connection: local
  gather_facts: true
  become: false

  vars_prompt:
    - name: bootstrap_sudo_password
      prompt: BECOME password
      private: true

  vars:
    ansible_become_password: "{{ bootstrap_sudo_password }}"

  roles:
    - role: homebrew
