---
# ==============================================================================
# SPACES SETTINGS
# ==============================================================================

- name: Spaces | Use separate spaces per display
  tags: [macos]
  community.general.osx_defaults:
    domain: com.apple.spaces
    key: spans-displays
    type: bool
    value: false

- name: Spaces | Switch to app's Space when activated
  tags: [macos]
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleSpacesSwitchOnActivate
    type: bool
    value: true
